function Nm_xi_zeta = Shape_zeta_(L,H,W,xi,eta,zeta)
%Shape_zeta_
%    Nm_xi_zeta = Shape_zeta_(L,H,W,XI,ETA,ZETA)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    29-Jul-2025 13:36:51

t2 = xi+1.0;
t3 = xi-1.0;
t4 = (W.*t2)./4.0;
t5 = (W.*t3)./4.0;
t6 = -t5;
Nm_xi_zeta = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t6,0.0,0.0,0.0,t6,0.0,0.0,0.0,t6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t4,0.0,0.0,0.0,t4,0.0,0.0,0.0,t4],[3,24]);
end
