function out1 = Af1(e01,e11,e21,e31)
%Af1
%    OUT1 = Af1(E01,E11,E21,E31)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    11-Sep-2025 19:07:52

t2 = e01.^2;
t3 = e01.*e11.*2.0;
t4 = e01.*e21.*2.0;
t5 = e01.*e31.*2.0;
t6 = e11.*e21.*2.0;
t7 = e11.*e31.*2.0;
t8 = e21.*e31.*2.0;
t9 = t2.*2.0;
out1 = reshape([t9+e11.^2.*2.0-1.0,t5+t6,-t4+t7,-t5+t6,t9+e21.^2.*2.0-1.0,t3+t8,t4+t7,-t3+t8,t9+e31.^2.*2.0-1.0],[3,3]);
end
