function out1 = Af2(e02,e12,e22,e32)
%Af2
%    OUT1 = Af2(E02,E12,E22,E32)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    28-Nov-2025 12:45:43

t2 = e02.^2;
t3 = e02.*e12.*2.0;
t4 = e02.*e22.*2.0;
t5 = e02.*e32.*2.0;
t6 = e12.*e22.*2.0;
t7 = e12.*e32.*2.0;
t8 = e22.*e32.*2.0;
t9 = t2.*2.0;
out1 = reshape([t9+e12.^2.*2.0-1.0,t5+t6,-t4+t7,-t5+t6,t9+e22.^2.*2.0-1.0,t3+t8,t4+t7,-t3+t8,t9+e32.^2.*2.0-1.0],[3,3]);
end
