function out1 = Af3(e03,e13,e23,e33)
%Af3
%    OUT1 = Af3(E03,E13,E23,E33)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Sep-2025 17:50:54

t2 = e03.^2;
t3 = e03.*e13.*2.0;
t4 = e03.*e23.*2.0;
t5 = e03.*e33.*2.0;
t6 = e13.*e23.*2.0;
t7 = e13.*e33.*2.0;
t8 = e23.*e33.*2.0;
t9 = t2.*2.0;
out1 = reshape([t9+e13.^2.*2.0-1.0,t5+t6,-t4+t7,-t5+t6,t9+e23.^2.*2.0-1.0,t3+t8,t4+t7,-t3+t8,t9+e33.^2.*2.0-1.0],[3,3]);
end
