function Jac = Jac(e03,e13,e23,e33,u1x,u1y,u1z)
%Jac
%    Jac = Jac(E03,E13,E23,E33,U1X,U1Y,U1Z)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Jul-2024 13:33:56

t2 = e03.*u1x.*2.0;
t3 = e13.*u1x.*2.0;
t4 = e23.*u1x.*2.0;
t5 = e33.*u1x.*2.0;
t6 = e03.*u1y.*2.0;
t7 = e13.*u1y.*2.0;
t8 = e23.*u1y.*2.0;
t9 = e33.*u1y.*2.0;
t10 = e03.*u1z.*2.0;
t11 = e13.*u1z.*2.0;
t12 = e23.*u1z.*2.0;
t13 = e33.*u1z.*2.0;
Jac = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-t9+t12+e03.*u1x.*4.0,t5-t11+e03.*u1y.*4.0,-t4+t7+e03.*u1z.*4.0,t8+t13+e13.*u1x.*4.0,t4-t10,t5+t6,t7+t10,t3+t13+e23.*u1y.*4.0,-t2+t9,-t6+t11,t2+t12,t3+t8+e33.*u1z.*4.0],[3,7]);
end
