function Jac2 = Jac2(e02,e12,e22,e32,u2x,u2y,u2z)
%Jac2
%    Jac2 = Jac2(E02,E12,E22,E32,U2X,U2Y,U2Z)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Jul-2024 13:28:56

t2 = e02.*u2x.*2.0;
t3 = e12.*u2x.*2.0;
t4 = e22.*u2x.*2.0;
t5 = e32.*u2x.*2.0;
t6 = e02.*u2y.*2.0;
t7 = e12.*u2y.*2.0;
t8 = e22.*u2y.*2.0;
t9 = e32.*u2y.*2.0;
t10 = e02.*u2z.*2.0;
t11 = e12.*u2z.*2.0;
t12 = e22.*u2z.*2.0;
t13 = e32.*u2z.*2.0;
Jac2 = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-t9+t12+e02.*u2x.*4.0,t5-t11+e02.*u2y.*4.0,-t4+t7+e02.*u2z.*4.0,t8+t13+e12.*u2x.*4.0,t4-t10,t5+t6,t7+t10,t3+t13+e22.*u2y.*4.0,-t2+t9,-t6+t11,t2+t12,t3+t8+e32.*u2z.*4.0],[3,7]);
end
