function Nm_xi_xi = Shape_xi_(L,H,W,xi,eta,zeta)
%Shape_xi_
%    Nm_xi_xi = Shape_xi_(L,H,W,XI,ETA,ZETA)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    03-Jun-2025 16:00:12

t2 = xi.*2.0;
t3 = xi+1.0;
t4 = H.*eta.*xi;
t5 = W.*xi.*zeta;
t7 = xi-1.0;
t8 = xi+1.0./2.0;
t11 = xi-1.0./2.0;
t6 = -t2;
t9 = -t4;
t10 = -t5;
t12 = t4./4.0;
t13 = t5./4.0;
t14 = (W.*t3.*zeta)./4.0;
t15 = (H.*eta.*t3)./4.0;
t16 = (W.*t7.*zeta)./4.0;
t17 = (H.*eta.*t7)./4.0;
t18 = t13+t14;
t19 = t12+t15;
t20 = t13+t16;
t21 = t12+t17;
Nm_xi_xi = reshape([t11,0.0,0.0,0.0,t11,0.0,0.0,0.0,t11,t21,0.0,0.0,0.0,t21,0.0,0.0,0.0,t21,t20,0.0,0.0,0.0,t20,0.0,0.0,0.0,t20,t6,0.0,0.0,0.0,t6,0.0,0.0,0.0,t6,t9,0.0,0.0,0.0,t9,0.0,0.0,0.0,t9,t10,0.0,0.0,0.0,t10,0.0,0.0,0.0,t10,t8,0.0,0.0,0.0,t8,0.0,0.0,0.0,t8,t19,0.0,0.0,0.0,t19,0.0,0.0,0.0,t19,t18,0.0,0.0,0.0,t18,0.0,0.0,0.0,t18],[3,27]);
end
