function A = Rotationmatrix_euler_parameter(x4,x5,x6,x7)
%Rotationmatrix_euler_parameter
%    A = Rotationmatrix_euler_parameter(X4,X5,X6,X7)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    28-Aug-2025 11:20:58

t2 = x4.^2;
t3 = x4.*x5.*2.0;
t4 = x4.*x6.*2.0;
t5 = x4.*x7.*2.0;
t6 = x5.*x6.*2.0;
t7 = x5.*x7.*2.0;
t8 = x6.*x7.*2.0;
t9 = t2.*2.0;
A = reshape([t9+x5.^2.*2.0-1.0,t5+t6,-t4+t7,-t5+t6,t9+x6.^2.*2.0-1.0,t3+t8,t4+t7,-t3+t8,t9+x7.^2.*2.0-1.0],[3,3]);
end
